import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import { NavigationMenuDemo } from "@/components/my/navigation-m";
import List from "@/components/my/list";
import { AnimatedThemeToggler } from "@/components/ui/animated-theme-toggler";
import { Heart, ShoppingCart, UserRound } from "lucide-react";
import { Input } from "@/components/ui/input";
import Image from "next/image";
import Link from "next/link";

const figtree = Figtree({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "SpazioLK",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", figtree.variable)}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col py-8 px-20">
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          disableTransitionOnChange
        >
          <div>
            <div className="flex justify-between items-center">
              {/* logo */}
              <div>
                <div className="relative h-5 w-auto ">
                  <Link href={'/'}>
                    <Image
                      src="/company-logo.svg"
                      alt="Product"
                      width={100}
                      height={100}
                      className="object-cover"
                    />
                  </Link>
                </div>
              </div>

              {/* //search */}
              <div className="w-100">
                <Input placeholder="Search for Products" />
              </div>

              {/* //profile,fav,cart */}
              <div>
                <div className="flex items-center gap-5">
                  <UserRound className="h-5 w-5" />
                  <Heart className="h-5 w-5" />
                  <ShoppingCart className="h-5 w-5" />
                  <AnimatedThemeToggler />
                </div>
              </div>
            </div>
            <div className="my-5 -pl-5 flex justify-center ">
              <NavigationMenuDemo />
            </div>
            <div>{children}</div>
            <div className="bg-muted-foreground/5 flex justify-between p-10">
              <List />
              <List />
              <List />
              <List />
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
